# Generated by Django 3.0rc1 on 2019-12-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blogpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='This is my slug'),
        ),
    ]
